[package]
name = "yam"
description = "http server,router and client"
version = "0.1.0"
edition = "2024"


[workspace]
resolver = "3"
members = [".","server", "router","client"]

[dependencies]
yam-server = { path = "server" }
yam-router = { path = "router" }
yam-client = { path = "client" }


tokio = { version="1.52.3", features=["full"] }
